language: php

sudo: true

addons:
  firefox: "47.0.1"
  apt:
    packages:
      - chromium-chromedriver


services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.2

env:
 global:
  - MOODLE_BRANCH=MOODLE_36_STABLE
 matrix:
  - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat